steps:
  # 1. Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '--build-arg'
      - 'FIREBASE_API_KEY=$_FIREBASE_API_KEY'
      - '--build-arg'
      - 'GEMINI_API_KEY=$_GEMINI_API_KEY'
      - '-t'
      - 'gcr.io/$PROJECT_ID/anipink-anime-manager:$COMMIT_SHA'
      - '.'

  # 2. Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/anipink-anime-manager:$COMMIT_SHA']

  # 3. Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'anipink-anime-manager'
      - '--image'
      - 'gcr.io/$PROJECT_ID/anipink-anime-manager:$COMMIT_SHA'
      - '--region'
      - 'us-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated' # Or authenticated, depending on preference. Public web apps usually allow unauth.

images:
  - 'gcr.io/$PROJECT_ID/anipink-anime-manager:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
