steps:
  # 1. Build the Docker image
  # We use 'sh -c' to explicitly handle variable expansion and debugging
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "*****************************************************************"
        echo "DEBUG: Verifying Build Arguments..."
        
        # Check variables and print lengths (masking values)
        if [ -z "$_FIREBASE_API_KEY" ]; then 
          echo "ERROR: _FIREBASE_API_KEY is empty or missing!"
          exit 1
        else
          echo "OK: _FIREBASE_API_KEY is set (length=$(echo -n $_FIREBASE_API_KEY | wc -c))"
        fi

        if [ -z "$_GEMINI_API_KEY" ]; then 
          echo "ERROR: _GEMINI_API_KEY is empty or missing!"
          exit 1
        else
          echo "OK: _GEMINI_API_KEY is set (length=$(echo -n $_GEMINI_API_KEY | wc -c))"
        fi
        
        echo "*****************************************************************"
        echo "Starting Docker Build..."
        
        docker build \
          --build-arg FIREBASE_API_KEY="${_FIREBASE_API_KEY}" \
          --build-arg GEMINI_API_KEY="${_GEMINI_API_KEY}" \
          -t gcr.io/$PROJECT_ID/anipink-anime-manager:$COMMIT_SHA \
          .

  # 2. Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/anipink-anime-manager:$COMMIT_SHA']

  # 3. Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'anipink-anime-manager'
      - '--image'
      - 'gcr.io/$PROJECT_ID/anipink-anime-manager:$COMMIT_SHA'
      - '--region'
      - 'us-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/anipink-anime-manager:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
